const productData = {
  productItems: [
    {
      id: "1",
      image: "./picture/product1watch1.jpg",
      title: "Noise pro3",
      price: "150",
      disprice: "280",
    },
    {
      id: "2",
      image: "./picture/product2watch2.jpg",
      title: "BVLGARI",
      price: "210",
      disprice: "230",
    },
    {
      id: "3",
      image: "./picture/product3watch3.jpg",
      title: "Titan",
      price: "125",
      disprice: "200",
    },
    {
      id: "4",
      image: "./picture/product4watch4.jpg",
      title: "casio g-shock",
      price: "200",
      disprice: "230",
    },
    {
      id: "5",
      image: "./picture/product5watch5.jpg",
      title: "Fastrack",
      price: "115",
      disprice: "210",
    },
    {
      id: "6",
      image: "./picture/product6mencloth1.jpg",
      title: "netplay",
      price: "40",
      disprice: "70",
    },
    {
      id: "7",
      image: "./picture/product7mencloth2.jpg",
      title: "Allen Solly",
      price: "70",
      disprice: "80",
    },
    {
      id: "8",
      image: "./picture/product8mencloth3.jpg",
      title: "proline",
      price: "65",
      disprice: "90",
    },
    {
      id: "9",
      image: "./picture/product9mencloth4.jpg",
      title: "levi's",
      price: "90",
      disprice: "95",
    },
    {
      id: "10",
      image: "./picture/product10mencloth5.jpeg",
      title: "playboy",
      price: "60",
      disprice: "63",
    },
    {
      id: "11",
      image: "./picture/product1shoes1.jpg",
      title: "puma",
      price: "70",
      disprice: "75",
    },
    {
      id: "12",
      image: "./picture/product7shoes7.jpg",
      title: "lee cooper",
      price: "70",
      disprice: "80",
    },
    {
      id: "13",
      image: "./picture/product3shoes3.webp",
      title: "sandals",
      price: "60",
      disprice: "80",
    },
    {
      id: "14",
      image: "./picture/product4shoes4.webp",
      title: "sketchers",
      price: "65",
      disprice: "95",
    },
    {
      id: "15",
      image: "./picture/product5shoes5.jpg",
      title: "sparx",
      price: "59",
      disprice: "70",
    },
    {
      id: "16",
      image: "./picture/product1womencloth1.jpg",
      title: "levi's",
      price: "35",
      disprice: "60",
    },
    {
      id: "17",
      image: "./picture/product2womencloth2.webp",
      title: "denim",
      price: "42",
      disprice: "50",
    },
    {
      id: "18",
      image: "./picture/product3womencloth3.webp",
      title: "kurta's",
      price: "30",
      disprice: "50",
    },
    {
      id: "19",
      image: "./picture/product4womencloth4.png",
      title: "western",
      price: "35",
      disprice: "45",
    },
    {
      id: "20",
      image: "./picture/product5womencloth5.jpg",
      title: "lavie",
      price: "30",
      disprice: "40",
    },
  ],
};

export default productData;
